# Looks like the usual ~/.nushell/ also has a history file, and a plugins file.
# I'm ignoring the history, looking to setup impermance which will wipe that regularly
# Plugins I'll probably do more once nu's updates for plugins get a bit more popular and I actually start using them, the one from my previous arch install looks like it was some autogenerated rust stuff, so I'm not gonna bother porting that manually.

{
  lib,
  config,
  pkgs,
  inputs,
  ...
}:

let
  inherit (lib) types mkEnableOption mkIf;
  cfg = config.polytope.tools.nushell;
in
{
  options.polytope.tools.nushell = {
    enable = mkEnableOption "Nushell";
  };

  config = mkIf cfg.enable {

    programs.nushell = {
      enable = true;
      configFile.source = ./config/config.nu;
      envFile.source = ./config/env.nu;
    };
  };
}
