# Looks like the usual ~/.nushell/ also has a history file, and a plugins file.
# I'm ignoring the history, looking to setup impermance which will wipe that regularly
# Plugins I'll probably do more once nu's updates for plugins get a bit more popular and I actually start using them, the one from my previous arch install looks like it was some autogenerated rust stuff, so I'm not gonna bother porting that manually.

{
  lib,
  config,
  pkgs,
  inputs,
  ...
}:

let
  inherit (lib) types mkEnableOption mkIf;
  cfg = config.polytope.tools.tealdeer;
in
{
  options.polytope.tools.tealdeer = {
    enable = mkEnableOption "Tealdeer";
  };

  config = mkIf cfg.enable {

    programs.tealdeer = {
      enable = true;
      settings.updates.auto_update = true;
      #settings.updates.auto_update_interval_hours = 48;
    };
  };
}
